//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinonims.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinonims.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agraïments.
        /// </summary>
        public static string Agraiments {
            get {
                return ResourceManager.GetString("Agraiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinònims i associacions.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.bitsdelocos.es/ca/openthesaurus.
        /// </summary>
        public static string AppPrivacyURL {
            get {
                return ResourceManager.GetString("AppPrivacyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donatiu per l&apos;aplicació.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;ha de tenir accés a Internet.
        /// </summary>
        public static string InternetNecesario {
            get {
                return ResourceManager.GetString("InternetNecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar les metadades de la petició.
        /// </summary>
        public static string MostrarMetaData {
            get {
                return ResourceManager.GetString("MostrarMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string Peticio {
            get {
                return ResourceManager.GetString("Peticio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca-ES.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introdueix la paraula a cercar.
        /// </summary>
        public static string TextSinonim {
            get {
                return ResourceManager.GetString("TextSinonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinònims.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre nosaltres.
        /// </summary>
        public static string TxtAbout {
            get {
                return ResourceManager.GetString("TxtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacti amb nosaltres.
        /// </summary>
        public static string TxtContacto {
            get {
                return ResourceManager.GetString("TxtContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informació:.
        /// </summary>
        public static string TxtInfo {
            get {
                return ResourceManager.GetString("TxtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string TxtLegal {
            get {
                return ResourceManager.GetString("TxtLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol·lítica de privadesa.
        /// </summary>
        public static string TxtPrivacidad {
            get {
                return ResourceManager.GetString("TxtPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termes del Servei.
        /// </summary>
        public static string TxtTerminos {
            get {
                return ResourceManager.GetString("TxtTerminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versió: .
        /// </summary>
        public static string TxtVersion {
            get {
                return ResourceManager.GetString("TxtVersion", resourceCulture);
            }
        }
    }
}
